In [2]:
import numpy as np

In [51]:
#example
raw = """5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526"""

In [58]:
# real input
raw = """7612648217
7617237672
2853871836
7214367135
1533365614
6258172862
5377675583
5613268278
8381134465
3445428733"""

In [47]:
#small example
raw = """11111
19991
19191
19991
11111"""

In [62]:
grid = np.array([list(line) for line in raw.split()], dtype=np.int_)

print(grid)

flash_count = 0
for t in range(400):
    
    grid += 1

    flashed = np.zeros(grid.shape, dtype=np.bool_)    
    
    while ((grid > 9) & ~flashed).any():
        new_flashed = (grid > 9) & ~flashed
        flashed[grid > 9] = True
        grid[flashed] = 0
        
        for i in range(grid.shape[0]):
            for j in range(grid.shape[1]):
                if new_flashed[i,j]:
                    grid[max(i - 1, 0):i + 2,max(j - 1, 0):j + 2] += 1        
            
            
    grid[flashed] = 0
    if len(grid[flashed]) == len(grid.flat):
        print(t + 1)
        break
    flash_count += len(grid[flashed])
    if t + 1 == 100:
        print(flash_count)


[[7 6 1 2 6 4 8 2 1 7]
 [7 6 1 7 2 3 7 6 7 2]
 [2 8 5 3 8 7 1 8 3 6]
 [7 2 1 4 3 6 7 1 3 5]
 [1 5 3 3 3 6 5 6 1 4]
 [6 2 5 8 1 7 2 8 6 2]
 [5 3 7 7 6 7 5 5 8 3]
 [5 6 1 3 2 6 8 2 7 8]
 [8 3 8 1 1 3 4 4 6 5]
 [3 4 4 5 4 2 8 7 3 3]]
1739
324
