In [2]:
import numpy as np

In [3]:
example = """6,10
0,14
9,10
0,3
10,4
4,11
6,0
6,12
4,1
0,13
10,12
3,4
3,0
8,4
1,10
2,14
8,10
9,0

fold along y=7
fold along x=5"""

In [27]:
with open('2021-12-13_input') as f:
    puzzle = f.read().strip()

In [39]:
points, folds = puzzle.split('\n\n')
points = points.split()
folds = folds.split('\n')

points = np.array([point.split(',') for point in points], dtype=np.int_)

sheet = np.zeros((points[:,0].max() + 1, points[:,1].max() + 2), dtype=np.int_)

for point in points:
    sheet[point[0], point[1]] = 1
    
print(sheet.T)
print(sheet.shape)



for fold in folds:
    
    print(fold.split('='))
    
    line = int(fold.split('=')[-1])
    
    if 'y=' in fold:
        
        upper = sheet[:,:line]
        lower = sheet[:,line + 1:]
        lower = lower[:,::-1]
        sheet = upper | lower
        print(sheet.T)
        print(sheet.sum())
        
        
    else:
        left = sheet[:line]
        right = sheet[line + 1:]
        right = right[::-1]
        sheet = left | right
        print(sheet.T)
        print(sheet.sum())
        

for line in sheet.T:
    
    string = ''.join([str(n) for n in line])
    
    string = string.replace('0', ' ')
    string = string.replace('1', '█')
    
    print(string)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(1311, 895)
['fold along x', '655']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
788
['fold along y', '447']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
656
['fold along x', '327']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
546
['fold along y', '223']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
463
['fold along x', '163']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
392
['fold along y', '111']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 

In [ ]:
for line in 