In [14]:
import datetime
from queue import PriorityQueue

import numpy as np


In [2]:
example = """1163751742
1381373672
2136511328
3694931569
7463417111
1319128137
1359912421
3125421639
1293138521
2311944581"""

In [3]:
with open('2021-12-15_input') as f:
    puzzle = f.read().strip()

In [17]:
#part one
start = datetime.datetime.now()
grid = np.array([list(line) for line in example.split()], dtype=np.int_)

grid = np.array([list(line) for line in puzzle.split()], dtype=np.int_)
print(grid.T)

graph = {}

for i in range(grid.shape[0]):
    for j in range(grid.shape[1]):
        
        
        coord = (i, j, grid[i, j])
        
        if i:
            previous = (i - 1, j)
            if previous in graph:
                graph[previous].append(coord)
            else:
                graph[previous] = [coord]
                
        if i < grid.shape[0] - 1:
            previous = (i + 1, j)
            if previous in graph:
                graph[previous].append(coord)
            else:
                graph[previous] = [coord]
                
        if j:
            previous = (i, j - 1)
            if previous in graph:
                graph[previous].append(coord)
            else:
                graph[previous] = [coord]  
                
        if j < grid.shape[1] - 1:
            previous = (i, j + 1)
            if previous in graph:
                graph[previous].append(coord)
            else:
                graph[previous] = [coord]                
                
# print(graph)

vertices = set(graph.keys())
distances = {point:np.inf for point in vertices}
distances[(0,0)] = 0
previous = {point:None for point in vertices}

# print((0, 0) in vertices)
# print(distances[(0,0)])
# print(graph[(0, 0)])

while vertices:
    minimum = np.inf
    u = None
    for vertex in vertices:
        if distances[vertex] < minimum:
            minimum = distances[vertex]
            u = vertex
    
    vertices = vertices - set([u])
       
    for adjacent in graph[u]:

        if adjacent[:2] not in vertices:
            continue
            
        alt = distances[u] + adjacent[2]
        if alt < distances[adjacent[:2]]:
            distances[adjacent[:2]] = alt
            previous[adjacent[:2]] = u
                        
# print(distances)
print(distances[(grid.shape[0] - 1, grid.shape[1] - 1)])
print(datetime.datetime.now() - start)

[[9 6 4 ... 6 5 1]
 [3 7 1 ... 7 8 6]
 [1 8 9 ... 9 1 1]
 ...
 [9 9 8 ... 9 8 9]
 [9 2 9 ... 6 8 9]
 [5 1 7 ... 3 9 8]]
698
0:03:22.616957


In [18]:
#faster part one
start = datetime.datetime.now()
grid = np.array([list(line) for line in example.split()], dtype=np.int_)

grid = np.array([list(line) for line in puzzle.split()], dtype=np.int_)
print(grid.T)

graph = {}

for i in range(grid.shape[0]):
    for j in range(grid.shape[1]):
        
        
        coord = (i, j, grid[i, j])
        
        if i:
            previous = (i - 1, j)
            if previous in graph:
                graph[previous].append(coord)
            else:
                graph[previous] = [coord]
                
        if i < grid.shape[0] - 1:
            previous = (i + 1, j)
            if previous in graph:
                graph[previous].append(coord)
            else:
                graph[previous] = [coord]
                
        if j:
            previous = (i, j - 1)
            if previous in graph:
                graph[previous].append(coord)
            else:
                graph[previous] = [coord]  
                
        if j < grid.shape[1] - 1:
            previous = (i, j + 1)
            if previous in graph:
                graph[previous].append(coord)
            else:
                graph[previous] = [coord]                
                
# print(graph)


distances = {point:np.inf for point in graph.keys()}
distances[(0,0)] = 0

pq = PriorityQueue()
pq.put((0, (0, 0)))
visited = []

while not pq.empty():

    dist, vertex = pq.get()
    visited.append(vertex)
       
    for adjacent in graph[vertex]:
        if adjacent[:2] in visited:
            continue
            
        alt = distances[vertex] + adjacent[2]
        if alt < distances[adjacent[:2]]:
            pq.put((alt, adjacent[:2]))
            distances[adjacent[:2]] = alt
                        
# print(distances)
print(distances[(grid.shape[0] - 1, grid.shape[1] - 1)])
print(datetime.datetime.now() - start)

[[9 6 4 ... 6 5 1]
 [3 7 1 ... 7 8 6]
 [1 8 9 ... 9 1 1]
 ...
 [9 9 8 ... 9 8 9]
 [9 2 9 ... 6 8 9]
 [5 1 7 ... 3 9 8]]
698
0:00:11.318851


In [19]:
#part two
grid = np.array([list(line) for line in example.split()], dtype=np.int_)
grid = np.array([list(line) for line in puzzle.split()], dtype=np.int_)
print(grid)

large_grid = np.zeros((grid.shape[0] * 5, grid.shape[1] * 5), dtype=np.int_)

for i in range(5):
    for j in range(5):
        large_grid[grid.shape[0] * i:grid.shape[0] * (i + 1), grid.shape[1] * j:grid.shape[1] * (j + 1)] = grid + j + i

large_grid = large_grid % 9
large_grid[large_grid == 0] = 9
print(large_grid)
grid = large_grid

graph = {}

for i in range(grid.shape[0]):
    for j in range(grid.shape[1]):
        
        
        coord = (i, j, grid[i, j])
        
        if i:
            previous = (i - 1, j)
            if previous in graph:
                graph[previous].append(coord)
            else:
                graph[previous] = [coord]
                
        if i < grid.shape[0] - 1:
            previous = (i + 1, j)
            if previous in graph:
                graph[previous].append(coord)
            else:
                graph[previous] = [coord]
                
        if j:
            previous = (i, j - 1)
            if previous in graph:
                graph[previous].append(coord)
            else:
                graph[previous] = [coord]  
                
        if j < grid.shape[1] - 1:
            previous = (i, j + 1)
            if previous in graph:
                graph[previous].append(coord)
            else:
                graph[previous] = [coord]                
                
# print(graph)

distances = {point:np.inf for point in graph.keys()}
distances[(0,0)] = 0

pq = PriorityQueue()
pq.put((0, (0, 0)))
visited = []

while not pq.empty():

    dist, vertex = pq.get()
    visited.append(vertex)
       
    for adjacent in graph[vertex]:
        if adjacent[:2] in visited:
            continue
            
        alt = distances[vertex] + adjacent[2]
        if alt < distances[adjacent[:2]]:
            pq.put((alt, adjacent[:2]))
            distances[adjacent[:2]] = alt
                        
# print(distances)
print(distances[(grid.shape[0] - 1, grid.shape[1] - 1)])
    

[[9 3 1 ... 9 9 5]
 [6 7 8 ... 9 2 1]
 [4 1 9 ... 8 9 7]
 ...
 [6 7 9 ... 9 6 3]
 [5 8 1 ... 8 8 9]
 [1 6 1 ... 9 9 8]]
[[9 3 1 ... 4 4 9]
 [6 7 8 ... 4 6 5]
 [4 1 9 ... 3 4 2]
 ...
 [1 2 4 ... 8 5 2]
 [9 3 5 ... 7 7 8]
 [5 1 5 ... 8 8 7]]
3022
